name = "MoMo"
license = "MIT"
licenselink = "https://github.com/fantasticmao/momo/blob/main/LICENSE"
description = ""
homepage = "https://github.com/fantasticmao/momo"
tags = ["personal"]
features = []
min_version = "0.41.0"

[author]
name = "fantasticmao"
homepage = "https://github.com/fantasticmao"
